<h3><?php echo $this->__('Latest news from Packt') ?></h3>
<table>
<?php foreach($this->getNewsList() as $item): ?>
<tr>
<td><img src="<?php echo Mage::getBaseUrl('media') . 'news'
. DS . $item['filename'] ?>" alt="<?php echo $item['title']
?>" width="64" height="64" style="border: 1px solid
#d5d5d5;padding:3px;margin-right: 10px;" /></td>
<td>
<h5><?php echo $item['title'] ?></h5>
<p><?php echo $this->limitCharacter($item['content'], 180, "
<a href='/news/index/view/id/".$item['news_id']."'>read more</a>")
?></p>
</td>
</tr>
<?php endforeach; ?>
</table>